### ISSUE TITLE
Can you provide the code of ORCA-vitB16? If yes, thank you very much

### ISSUE THREAD

**Issue by zhoulixiang38** [ThalesGroup/pim-generalized-category-discovery#3]
Can you provide the code of ORCA-vitB16? If yes, thank you very much

**Comment by tds-fchiaroni** [comment]
Hello @zhoulixiang38 ,

Thank you for your interest! However, our repository is focused on our own method "PIM" and does not include the code of other methods such as ORCA. I recommend checking repositories specifically related to ORCA method and ViT-B model for the information you need.

Best,
Florent
